// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace XamarinEvolveIOS
{
	public partial class ProfileViewController : UITableViewController
	{
		public ProfileViewController (IntPtr handle) : base (handle)
		{

		}

		public override void LoadView ()
		{
			base.LoadView ();
			TableView.DataSource = new LocalUserProfileDataSource (
				new LocalUserProfile () {
				UserName = "billholmes54",
				FullName = "Bill Holmes",
				City = "Pittsburgh, PA",
				Company = "Slap Holmes Productions",
				Title = "CEO",
				EMail = "bill@mobillholmes.com",
				Phone = "(555)-555-5555"
			});
		}
	}

	public class LocalUserProfileDataSource : UITableViewDataSource
	{
		public LocalUserProfileDataSource (LocalUserProfile profile)
		{
			UserProfile = profile;
		}
		
		public LocalUserProfile UserProfile {get; private set;}
		
		#region UITableViewDataSource	
		
		public override int NumberOfSections (UITableView tableView)
		{
			return 3;
		}
		
		public override int RowsInSection (UITableView tableView, int section)
		{
			if (section == 0)
				return 2;

			if (section == 1)
				return 2;

			if (section == 2)
				return 2;

			throw new IndexOutOfRangeException ("section out of range");
		}		
		
		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell;

			switch (indexPath.Section)
			{
			case 0:
				cell = GetCellSectionOne (tableView, indexPath);
				break;
			case 1:
				cell = GetCellSectionTwo (tableView, indexPath);
				break;
			case 2:
				cell = GetCellSectionThree (tableView, indexPath);
				break;
				
			default:
				throw new IndexOutOfRangeException ("indexPath.Section out of range.");
			}

			return cell;
		}
		
		#endregion

		const string StringOnlyName = "UserProfile_StringOnly";

		static UITableViewCell GetStringOnlyCell (UITableView tableView, string value)
		{
			UITableViewCell cell = tableView.DequeueReusableCell (StringOnlyName);

			if (cell == null)
				cell = new UITableViewCell (UITableViewCellStyle.Default, StringOnlyName);

			cell.SelectionStyle = UITableViewCellSelectionStyle.None;

			cell.TextLabel.Text = value;

			return cell;
		}

		private UITableViewCell GetCellSectionOne (UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell;
			
			switch (indexPath.Row)
			{
			case 0:
				cell = GetStringOnlyCell (tableView, UserProfile.FullName);
				break;
			case 1:
				cell = GetStringOnlyCell (tableView, UserProfile.City);
				break;

			default:
				throw new IndexOutOfRangeException ("indexPath.Row out of range.");
			}
			
			return cell;
		}

		private UITableViewCell GetCellSectionTwo (UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell;
			
			switch (indexPath.Row)
			{
			case 0:
				cell = GetStringOnlyCell (tableView, UserProfile.Company);
				break;
			case 1:
				cell = GetStringOnlyCell (tableView, UserProfile.Title);
				break;
				
			default:
				throw new IndexOutOfRangeException ("indexPath.Row out of range.");
			}
			
			return cell;
		}

		private UITableViewCell GetCellSectionThree (UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell;
			
			switch (indexPath.Row)
			{
			case 0:
				cell = GetStringOnlyCell (tableView, UserProfile.EMail);
				break;
			case 1:
				cell = GetStringOnlyCell (tableView, UserProfile.Phone);
				break;
				
			default:
				throw new IndexOutOfRangeException ("indexPath.Row out of range.");
			}
			
			return cell;
		}
	}
	
	public class UserProfile
	{
		public string UserName {get; set;}
		public string FullName {get; set;}
		public string EMail {get; set;}
		public string City {get;set;}
		public string Company {get; set;}
		public string Title {get; set;}
		public string Phone {get;set;}
	}
	
	public class LocalUserProfile : UserProfile
	{
		
	}

}
