// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace XamarinEvolveIOS
{

	public partial class WelcomeTableViewController : UITableViewController
	{
		public WelcomeTableViewController (IntPtr handle) : base (handle)
		{
		}
	}


}
