#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinEvolveAndroid.Resource", IsApplication=true)]

namespace XamarinEvolveAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			XamarinEvolveSSLibraryAndroid.Resource.String.library_name = XamarinEvolveAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lightgrey = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blankavatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int Icon = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Text2 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int webView1 = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EvolveOnTheWebLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageAndSubtitleItem = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int Attendees = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int EvolveontheWeb = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Loading = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
