#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinEvolveAndroid.Resource", IsApplication=true)]

namespace XamarinEvolveAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			XamarinEvolveSSLibraryAndroid.Resource.String.library_name = XamarinEvolveAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lightgrey = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blankavatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int Icon = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Text2 = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int UserCityText = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int UserCompanyText = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int UserEMailText = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int UserNameText = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int UserPhoneText = 2131099669;
			
			// aapt resource value: 0x7f06000f
			public const int UserTitleText = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int avatarImageView = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout3 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout4 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout5 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout6 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout7 = 2131099667;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView2 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int textView3 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int textView4 = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int webView1 = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EvolveOnTheWebLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageAndSubtitleItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int UserDetailLayout = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int Attendees = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int EvolveontheWeb = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Loading = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Profile = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int company = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int email = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int phone = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int title = 2130968583;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
