#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinEvolveAndroid.Resource", IsApplication=true)]

namespace XamarinEvolveAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			XamarinEvolveSSLibraryAndroid.Resource.String.library_name = XamarinEvolveAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public const int Attendees = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Loading = 2130903043;
			
			// aapt resource value: 0x7f030001
			public const int app_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
